#
# Dockerfile for building MySQL images
# 
# https://github.com/addcn/docker-lnmp.git
#

FROM registry.docker-cn.com/library/mysql:5.7
MAINTAINER dodo <lhuibo@gmail.com>

ENV TZ "Asia/Shanghai"

# COPY config/my.cnf /etc/mysql/my.cnf